main: io.github.stonley890.App
name: Dreamvisitor
version: 1.3
api-version: 1.19
description: A plugin created by Bog for WoF:TNW to add various features.
author: Stonley890

commands:
  pausechat:
    description: Pauses chat for non-OPs.
    usage: /<command> 
    permission: minecraft.command.op
  aradio:
    description: Sends a message to all OPs.
    usage: /<command> <message>
    permission: minecraft.command.op
  radio:
    description: Sends a message to all staff.
    usage: /<command> <message>
  discord:
    description: Toggles Discord message visibility.
    usage: /<command>
  zoop:
    description: Vanish from Discord.
    usage: /<command>
    permission: minecraft.command.op
  softwhitelist:
    description: Add or remove a player to/from the soft whitelist.
    usage: /<command> <add|remove|list|on|off> <player>
    permission: minecraft.command.op