main: io.github.stonley890.App
name: Dreamvisitor
version: 1.0
api-version: 1.18
description: A plugin created by Bog for WoF:TNW to add Discord automation.
author: Stonley890

commands:
  offlineec:
    description: Get an offline player's Ender Chest.
    usage: /<command> 
  offlineinv:
    description: Get an offline player's inventory.
    usage: /<command>