main: io.github.stonley890.dreamvisitor.Dreamvisitor
name: Dreamvisitor
version: 2.1.0
api-version: 1.20
description: A plugin created by Bog for WoF:TNW to add various features.
author: Stonley890

commands:
  pausechat:
    description: Pauses chat for non-OPs.
    usage: /<command> 
    permission: dreamvisitor.pausechat
  aradio:
    description: Sends a message to all OPs.
    usage: /<command> <message>
    permission: minecraft.command.op
  radio:
    description: Sends a message to all staff.
    usage: /<command> <message>
    permission: dreamvisitor.radio
  tagradio:
    description: Sends a messages to all players with specified tag.
    usage: /<command> <tag> <message>
    permission: dreamvisitor.tagradio
  discord:
    description: Toggles Discord message visibility.
    usage: /<command>
  zoop:
    description: Vanish from Discord.
    usage: /<command>
    permission: dreamvisitor.zoop
  softwhitelist:
    description: Add or remove a player to/from the soft whitelist.
    usage: /<command> <add|remove|list|on|off> [player]
    permission: dreamvisitor.softwhitelist
  playerlimit:
    description: Override server player limit.
    usage: /<command> <number of players (set -1 to disable)>
    permission: dreamvisitor.playerlimit
  togglepvp:
    description: Globally disable PvP.
    usage: /<command>
    permission: dreanvisitor.togglepvp
  pausebypass:
    description: Let player bypass pause.
    usage: /<command> <add|remove|list>
    permission: dreamvisitor.pausechat
  sethub:
    description: Set the hub location.
    usage: /<command>
    permission: minecraft.command.op
  hub:
    description: Teleport to the hub.
    usage: /<command>
  panic:
    description: Kicks all players and sets the player limit override to 0.
    usage: /<command>
    permission: dreamvisitor.panic
  reloadbot:
    description: Restarts the Dreamvisitor Discord bot
    usage: /<command>
    permission: minecraft.command.op
  itemblacklist:
    description: Access the item blacklist
    usage: /<command>
    permission: dreamvisitor.itemblacklist
  tribeupdate:
    description: Update Discord role based on in-game team
    usage: /<command> [player]
    permission: minecraft.command.op
  user:
    description: Get the details of a player
    usage: /<command> <username>
    permission: dreamvisitor.user

permissions:
  dreamvisitor.pausechat:
    description: Allows all chat pause commands
    default: op
  dreamvisitor.tagradio:
    description: Allows the tagradio command
    default: op
  dreamvisitor.zoop:
    description: Allows the zoop command
    default: op
  dreamvisitor.softwhitelist:
    description: Allows the softwhitelist command
    default: op
  dreamvisitor.playerlimit:
    description: Allows the playerlimit command
    default: op
  dreanvisitor.togglepvp:
    description: Allows the togglepvp command
    default: op
  dreamvisitor.panic:
    description: Allows the panic command
    default: op
  dreamvisitor.itemblacklist:
    description: Allows the itemblacklist command
    default: op
  dreamvisitor.user:
    description: Allows the user command
    default: op
  dreamvisitor.radio:
    description: Allows the radio command
    default: op