main: io.github.stonley890.App
name: Dreamvisitor
version: 1.7.1
api-version: 1.19
description: A plugin created by Bog for WoF:TNW to add various features.
author: Stonley890

commands:
  pausechat:
    description: Pauses chat for non-OPs.
    usage: /<command> 
    permission: minecraft.command.op
  aradio:
    description: Sends a message to all OPs.
    usage: /<command> <message>
    permission: minecraft.command.op
  radio:
    description: Sends a message to all staff.
    usage: /<command> <message>
  tagradio:
    description: Sends a messages to all players with specified tag.
    usage: /<command> <tag> <message>
    permission: minecraft.command.op
  discord:
    description: Toggles Discord message visibility.
    usage: /<command>
  zoop:
    description: Vanish from Discord.
    usage: /<command>
    permission: minecraft.command.op
  softwhitelist:
    description: Add or remove a player to/from the soft whitelist.
    usage: /<command> <add|remove|list|on|off> <player>
    permission: minecraft.command.op
  playerlimit:
    description: Override server player limit.
    usage: /<command> <number of players (set -1 to disable)>
    permission: minecraft.command.op
  togglepvp:
    description: Globally disable PvP.
    usage: /<command>
    permission: minecraft.command.op
  pausebypass:
    description: Let player bypass pause.
    usage: /command
    permission: minecraft.command.op